# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 瞬息
brief-intro: 电光石火、转瞬即逝
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://small-tailqwq.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: #gaohaoyang126
facebook_username: #gaohaoyang.water
github_username:  small-tailqwq
email: Small_tailqwq@qq.com
weibo_username: 5610377163
zhihu_username: 
linkedIn_username: 
dribbble_username: 

description_footer: 瞬息 转瞬即逝

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: #bemiku.disqus.com/count.js
City_shortname： MTAyMC80NzI2My8yMzc2Mw==

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 084e68676f7b0e5522ee147b0650e144
google_analytics_id: UA-150927766-1 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
port: 4001
